# Generated by Django 3.0.2 on 2020-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_converter', models.CharField(max_length=30, verbose_name='Конвертируемое число')),
                ('result_converter', models.CharField(max_length=30, verbose_name='Результат конвертации')),
            ],
            options={
                'verbose_name': 'Сохраненная конвертация',
                'verbose_name_plural': 'Сохраненные конвертации',
            },
        ),
    ]
