# Generated by Django 3.0.2 on 2020-01-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveconverter',
            name='ip_address',
            field=models.CharField(default='', max_length=256, verbose_name='IP'),
            preserve_default=False,
        ),
    ]
