# Generated by Django 3.0.2 on 2020-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_saveconverter_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveconverter',
            name='number_converter',
            field=models.CharField(max_length=30, verbose_name='Конвертация'),
        ),
        migrations.AlterField(
            model_name='saveconverter',
            name='result_converter',
            field=models.CharField(max_length=30, verbose_name='Результат'),
        ),
    ]
